server:
  port: 8080 #Tomcat端口
spring:
  dubbo:
    application:
      name: dubbo-server #应用名
    registry:
      address: zookeeper://localhost #zookeeper地址
      port: 2181 #提供注册的端口
    protocol:
      name: dubbo
      port: 20890 #dubbo服务暴露的端口
    scan: com.dubbo.demo.service.impl #扫描的包名